// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2xEP-XMPvFYuxWfoSwPFPwTCuBkWfIwQ',
    appId: '1:925139240938:web:e06d4d017555ec2efb5493',
    messagingSenderId: '925139240938',
    projectId: 'fir-app-e1152',
    authDomain: 'fir-app-e1152.firebaseapp.com',
    storageBucket: 'fir-app-e1152.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0KDqZn9WHePUcnMKy1mTSL0tGNa7L_gk',
    appId: '1:925139240938:android:5f0a12ca8f80058afb5493',
    messagingSenderId: '925139240938',
    projectId: 'fir-app-e1152',
    storageBucket: 'fir-app-e1152.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPxJ_ndMQt-gwqW8hDc6mO9dd9ovs_D_w',
    appId: '1:925139240938:ios:b3cab9fad9e8ba47fb5493',
    messagingSenderId: '925139240938',
    projectId: 'fir-app-e1152',
    storageBucket: 'fir-app-e1152.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPxJ_ndMQt-gwqW8hDc6mO9dd9ovs_D_w',
    appId: '1:925139240938:ios:b3cab9fad9e8ba47fb5493',
    messagingSenderId: '925139240938',
    projectId: 'fir-app-e1152',
    storageBucket: 'fir-app-e1152.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2xEP-XMPvFYuxWfoSwPFPwTCuBkWfIwQ',
    appId: '1:925139240938:web:a9c014b6a77dbd1cfb5493',
    messagingSenderId: '925139240938',
    projectId: 'fir-app-e1152',
    authDomain: 'fir-app-e1152.firebaseapp.com',
    storageBucket: 'fir-app-e1152.firebasestorage.app',
  );
}
